import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import ProductDetail from "../components/ProductDetail";
import PageTransition from "../components/PageTransition";

// Imagens estilizadas
import iphone15ProMaxImg from "../assets/images/iphone15promax_fancy.png";
import iphone15Img from "../assets/images/iphone15_fancy.png";
import iphone14ProMaxImg from "../assets/images/iphone14promax_fancy.png";
import iphone12ProImg from "../assets/images/iphone12pro_fancy.png";

// Imagens reais
import iphone15ProMaxReal1 from "../assets/images/IMG_3371.HEIC.png";
import iphone15ProMaxReal2 from "../assets/images/IMG_3396.png";
import iphone15Real1 from "../assets/images/IMG_3397.png";
import iphone15Real2 from "../assets/images/IMG_3375.png";
import iphone14ProMaxReal1 from "../assets/images/IMG_3401.png";
import iphone14ProMaxReal2 from "../assets/images/IMG_3381.png";
import iphone12ProReal1 from "../assets/images/IMG_3400.png";
import iphone12ProReal2 from "../assets/images/IMG_3380.png";

// Banco de dados de produtos
const productDatabase = {
  "iphones-seminovos": [
    {
      id: 1,
      model: "iPhone 15 Pro Max",
      storage: "256GB",
      color: "Titânio Natural",
      battery: "89%",
      originalPrice: "R$ 6.590,00",
      installmentPrice: "R$ 540,67",
      pixPrice: "R$ 5.690",
      details: "sem detalhes | garantia Apple até junho",
      image: iphone15ProMaxImg,
      realImages: [iphone15ProMaxReal1, iphone15ProMaxReal2],
      category: "iPhones Seminovos",
      specs:
        'Tela Super Retina XDR de 6,7", chip A17 Pro, câmera tripla de 48MP, 256GB de armazenamento',
    },
    {
      id: 2,
      model: "iPhone 15",
      storage: "256GB",
      color: "Preto",
      battery: "90%",
      originalPrice: "R$ 5.190,00",
      installmentPrice: "R$ 379,13",
      pixPrice: "R$ 3.990",
      details: "*pequeno detalhe na lateral",
      image: iphone15Img,
      realImages: [iphone15Real1, iphone15Real2],
      category: "iPhones Seminovos",
      specs:
        'Tela Super Retina XDR de 6,1", chip A16 Bionic, câmera dupla de 48MP, 256GB de armazenamento',
    },
    {
      id: 3,
      model: "iPhone 14 Pro Max",
      storage: "512GB",
      color: "Preto",
      battery: "81%",
      originalPrice: "R$ 5.900,00",
      installmentPrice: "R$ 465,60",
      pixPrice: "R$ 4.900",
      details: "*detalhes de capinha na borda",
      image: iphone14ProMaxImg,
      realImages: [iphone14ProMaxReal1, iphone14ProMaxReal2],
      category: "iPhones Seminovos",
      specs:
        'Tela Super Retina XDR de 6,7", chip A16 Bionic, câmera tripla de 48MP, 512GB de armazenamento',
    },
    {
      id: 4,
      model: "iPhone 14 Pro Max",
      storage: "256GB",
      color: "Roxo",
      battery: "87%",
      originalPrice: "R$ 5.300,00",
      installmentPrice: "R$ 441,85",
      pixPrice: "R$ 4.650",
      details: "*detalhe na lateral",
      image: iphone14ProMaxImg,
      realImages: [iphone14ProMaxReal1, iphone14ProMaxReal2],
      category: "iPhones Seminovos",
      specs:
        'Tela Super Retina XDR de 6,7", chip A16 Bionic, câmera tripla de 48MP, 256GB de armazenamento',
    },
    {
      id: 5,
      model: "iPhone 12 Pro",
      storage: "128GB",
      color: "Dourado",
      battery: "78%",
      originalPrice: "R$ 2.700,00",
      installmentPrice: "R$ 189,09",
      pixPrice: "R$ 1.990",
      details: "sem detalhes",
      image: iphone12ProImg,
      realImages: [iphone12ProReal1, iphone12ProReal2],
      category: "iPhones Seminovos",
      specs:
        'Tela Super Retina XDR de 6,1", chip A14 Bionic, câmera tripla de 12MP, 128GB de armazenamento',
    },
  ],

  "iphones-novos": [
    {
      id: 6,
      model: "iPhone 16 Pro Max",
      storage: "(1TB)",
      color:
        "Titânio Preto, Titânio Cinza/Natural, Titânio Branco, Titânio Deserto",
      battery: "100%",
      originalPrice: "R$ 14445.35",
      installmentPrice: "R$ 1160",
      pixPrice: "R$ 12.039",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela ~6.9", Chip A18 Pro, Câmera Ultra Wide 48MP, Zoom Óptico 5x, Wi-Fi 7, Botão de Captura, Bateria ~4676 mAh (Rumor)',
    },
    {
      id: 7,
      model: "iPhone 16 Pro",
      storage: "(1TB)",
      color:
        "Titânio Preto, Titânio Cinza/Natural, Titânio Branco, Titânio Deserto",
      battery: "100%",
      originalPrice: "R$ 13015.93",
      installmentPrice: "R$ 1061",
      pixPrice: "R$ 11.017",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela ~6.3", Chip A18 Pro, Câmera Ultra Wide 48MP, Zoom Óptico 5x, Wi-Fi 7, Botão de Captura, Bateria ~3355 mAh (Rumor)',
    },
    {
      id: 8,
      model: "iPhone 16 Pro Max",
      storage: "(512GB)",
      color:
        "Titânio Preto, Titânio Cinza/Natural, Titânio Branco, Titânio Deserto",
      battery: "100%",
      originalPrice: "R$ 12374.76",
      installmentPrice: "R$ 1023",
      pixPrice: "R$ 10.619",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela ~6.9", Chip A18 Pro, Câmera Ultra Wide 48MP, Zoom Óptico 5x, Wi-Fi 7, Botão de Captura, Bateria ~4676 mAh (Rumor)',
    },
    {
      id: 9,
      model: "iPhone 16 Pro",
      storage: "(512GB)",
      color:
        "Titânio Preto, Titânio Cinza/Natural, Titânio Branco, Titânio Deserto",
      battery: "100%",
      originalPrice: "R$ 10692.95",
      installmentPrice: "R$ 881",
      pixPrice: "R$ 9.142",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela ~6.3", Chip A18 Pro, Câmera Ultra Wide 48MP, Zoom Óptico 5x, Wi-Fi 7, Botão de Captura, Bateria ~3355 mAh (Rumor)',
    },
    {
      id: 10,
      model: "iPhone 15 Pro Max",
      storage: "(512GB)",
      color: "Titânio Preto, Titânio Branco, Titânio Azul, Titânio Natural",
      battery: "100%",
      originalPrice: "R$ 9527.68",
      installmentPrice: "R$ 826",
      pixPrice: "R$ 8.573",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela Super Retina XDR 6.7", Chip A17 Pro, Câmera Tripla 48MP, USB-C (USB 3), Titânio, Botão de Ação',
    },
    {
      id: 11,
      model: "iPhone 16 Pro Max",
      storage: "(256GB)",
      color:
        "Titânio Preto, Titânio Cinza/Natural, Titânio Branco, Titânio Deserto",
      battery: "100%",
      originalPrice: "R$ 9386.00",
      installmentPrice: "R$ 765",
      pixPrice: "R$ 7.937",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela ~6.9", Chip A18 Pro, Câmera Ultra Wide 48MP, Zoom Óptico 5x, Wi-Fi 7, Botão de Captura, Bateria ~4676 mAh (Rumor)',
    },
    {
      id: 12,
      model: "iPhone 16 Pro",
      storage: "(256GB)",
      color:
        "Titânio Preto, Titânio Cinza/Natural, Titânio Branco, Titânio Deserto",
      battery: "100%",
      originalPrice: "R$ 8415.00",
      installmentPrice: "R$ 710",
      pixPrice: "R$ 7.369",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela ~6.3", Chip A18 Pro, Câmera Ultra Wide 48MP, Zoom Óptico 5x, Wi-Fi 7, Botão de Captura, Bateria ~3355 mAh (Rumor)',
    },
    {
      id: 13,
      model: "iPhone 16 Plus",
      storage: "(256GB)",
      color: "Preto, Branco, Rosa, Teal, Ultramarino",
      battery: "100%",
      originalPrice: "R$ 8206.89",
      installmentPrice: "R$ 705",
      pixPrice: "R$ 7.323",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela 6.7", Chip A18, Câmera 48MP Fusion, Botão de Ação, Botão de Captura, USB-C (Rumor/Preliminar)',
    },
    {
      id: 14,
      model: "iPhone 16 Pro",
      storage: "(128GB)",
      color:
        "Titânio Preto, Titânio Cinza/Natural, Titânio Branco, Titânio Deserto",
      battery: "100%",
      originalPrice: "R$ 7580.61",
      installmentPrice: "R$ 644",
      pixPrice: "R$ 6.687",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela ~6.3", Chip A18 Pro, Câmera Ultra Wide 48MP, Zoom Óptico 5x, Wi-Fi 7, Botão de Captura, Bateria ~3355 mAh (Rumor)',
    },
    {
      id: 15,
      model: "iPhone 16 Plus",
      storage: "(128GB)",
      color: "Preto, Branco, Rosa, Teal, Ultramarino",
      battery: "100%",
      originalPrice: "R$ 7558.18",
      installmentPrice: "R$ 634",
      pixPrice: "R$ 6.585",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela 6.7", Chip A18, Câmera 48MP Fusion, Botão de Ação, Botão de Captura, USB-C (Rumor/Preliminar)',
    },
    {
      id: 16,
      model: "iPhone 16",
      storage: "(256GB)",
      color: "Preto, Branco, Rosa, Teal, Ultramarino",
      battery: "100%",
      originalPrice: "R$ 7295.39",
      installmentPrice: "R$ 618",
      pixPrice: "R$ 6.414",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela 6.1", Chip A18, Câmera 48MP Fusion, Botão de Ação, Botão de Captura, USB-C (Rumor/Preliminar)',
    },
    {
      id: 17,
      model: "iPhone 15",
      storage: "(256GB)",
      color: "Rosa, Amarelo, Verde, Azul, Preto",
      battery: "100%",
      originalPrice: "R$ 6994.64",
      installmentPrice: "R$ 563",
      pixPrice: "R$ 5.846",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela Super Retina XDR 6.1", Chip A16 Bionic, Câmera Dupla 48MP, Dynamic Island, USB-C (USB 2)',
    },
    {
      id: 18,
      model: "iPhone 16",
      storage: "(128GB)",
      color: "Preto, Branco, Rosa, Teal, Ultramarino",
      battery: "100%",
      originalPrice: "R$ 6417.93",
      installmentPrice: "R$ 519",
      pixPrice: "R$ 5.392",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela 6.1", Chip A18, Câmera 48MP Fusion, Botão de Ação, Botão de Captura, USB-C (Rumor/Preliminar)',
    },
    {
      id: 19,
      model: "iPhone 15",
      storage: "(128GB)",
      color: "Rosa, Amarelo, Verde, Azul, Preto",
      battery: "100%",
      originalPrice: "R$ 5436.39",
      installmentPrice: "R$ 468",
      pixPrice: "R$ 4.857",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela Super Retina XDR 6.1", Chip A16 Bionic, Câmera Dupla 48MP, Dynamic Island, USB-C (USB 2)',
    },
    {
      id: 20,
      model: "iPhone 16e",
      storage: "(128GB)",
      color: "Preto, Branco, Rosa, Teal, Ultramarino",
      battery: "100%",
      originalPrice: "R$ 4937.87",
      installmentPrice: "R$ 399",
      pixPrice: "R$ 4.142",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela 6.1", Chip A18, Câmera 48MP Fusion, Botão de Ação, Botão de Captura, USB-C (Rumor/Preliminar)',
    },
    {
      id: 21,
      model: "iPhone 14",
      storage: "(128GB)",
      color: "Meia-noite, Roxo, Estelar,RED, Azul, Amarelo",
      battery: "100%",
      originalPrice: "R$ 4716.15",
      installmentPrice: "R$ 410",
      pixPrice: "R$ 4.255",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela Super Retina XDR 6.1", Chip A15 Bionic (GPU 5-core), Câmera Dupla 12MP, Detecção de Acidente',
    },
    {
      id: 22,
      model: "iPhone 13",
      storage: "(128GB)",
      color: "RED, Estelar, Meia-noite, Azul, Rosa, Verde",
      battery: "100%",
      originalPrice: "R$ 4120.38",
      installmentPrice: "R$ 344",
      pixPrice: "R$ 3.573",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela Super Retina XDR 6.1", Chip A15 Bionic (GPU 4-core), Câmera Dupla 12MP, Modo Cinema',
    },
    {
      id: 23,
      model: "iPhone 11",
      storage: "(128GB)",
      color: "Preto, Verde, Amarelo, Roxo,RED, Branco",
      battery: "100%",
      originalPrice: "R$ 3546.81",
      installmentPrice: "R$ 297",
      pixPrice: "R$ 3.085",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela Liquid Retina HD LCD 6.1", Chip A13 Bionic, Câmera Dupla 12MP, Modo Noite',
    },
    {
      id: 24,
      model: "iPhone 12",
      storage: "(64GB)",
      color: "Preto, Branco,RED, Verde, Azul, Roxo",
      battery: "100%",
      originalPrice: "R$ 3551.58",
      installmentPrice: "R$ 289",
      pixPrice: "R$ 3.005",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela Super Retina XDR OLED 6.1", Chip A14 Bionic, Câmera Dupla 12MP, 5G, Ceramic Shield',
    },
    {
      id: 25,
      model: "iPhone 11",
      storage: "(64GB)",
      color: "Preto, Verde, Amarelo, Roxo,RED, Branco",
      battery: "100%",
      originalPrice: "R$ 2921.77",
      installmentPrice: "R$ 249",
      pixPrice: "R$ 2.585",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPhones Novos",
      specs:
        'Tela Liquid Retina HD LCD 6.1", Chip A13 Bionic, Câmera Dupla 12MP, Modo Noite',
    },
  ],

  macbooks: [
    {
      id: 26,
      model: 'MacBook Pro 16" M4 Max',
      storage: "(48GB RAM / 1TB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 37.014,06",
      installmentPrice: "12x R$ 3.151,00",
      pixPrice: "R$ 32.712,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 16.2", Chip M4 Max (14/16-core CPU, 32/40-core GPU), 3x Thunderbolt 5, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 27,
      model: 'MacBook Pro 16" M4 Max',
      storage: "(36GB RAM / 1TB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 35.063,34",
      installmentPrice: "12x R$ 2.823,00",
      pixPrice: "R$ 29.303,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 16.2", Chip M4 Max (14/16-core CPU, 32/40-core GPU), 3x Thunderbolt 5, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 28,
      model: 'MacBook Pro 14" M4 Max',
      storage: "(36GB RAM / 1TB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 377,44",
      installmentPrice: "12x R$ 031,00",
      pixPrice: "R$ 326,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 14.2", Chip M4 Max (14/16-core CPU, 32/40-core GPU), 3x Thunderbolt 5, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 29,
      model: 'MacBook Pro 16" M4 Pro',
      storage: "(48GB RAM / 512GB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 363,27",
      installmentPrice: "12x R$ 031,00",
      pixPrice: "R$ 326,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 16.2", Chip M4 Pro (14-core CPU, 20-core GPU), 3x Thunderbolt 5, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 30,
      model: 'MacBook Pro 16" M4 Pro',
      storage: "(24GB RAM / 512GB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 23.928,42",
      installmentPrice: "12x R$ 1.985,00",
      pixPrice: "R$ 20.610,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 16.2", Chip M4 Pro (14-core CPU, 20-core GPU), 3x Thunderbolt 5, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 31,
      model: 'MacBook Pro 14" M4',
      storage: "(24GB RAM / 1TB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 22.252,98",
      installmentPrice: "12x R$ 1.832,00",
      pixPrice: "R$ 19.019,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 14.2", Chip M4 (10-core CPU, 10-core GPU), 3x Thunderbolt 4, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 32,
      model: 'MacBook Pro 14" M4 Pro',
      storage: "(24GB RAM / 512GB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 18.840,71",
      installmentPrice: "12x R$ 1.602,00",
      pixPrice: "R$ 16.632,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 14.2", Chip M4 Pro (12/14-core CPU, 16/20-core GPU), 3x Thunderbolt 5, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 33,
      model: 'MacBook Pro 14" M4',
      storage: "(16GB RAM / 1TB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 16.336,43",
      installmentPrice: "12x R$ 1.394,00",
      pixPrice: "R$ 14.473,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 14.2", Chip M4 (10-core CPU, 10-core GPU), 3x Thunderbolt 4, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 34,
      model: 'MacBook Air 15"M4',
      storage: "(16GB RAM / 512GB SSD)",
      color: 'Cor para "MacBook Air 15"M4" não encontrada',
      battery: "100%",
      originalPrice: "R$ 14.640,16",
      installmentPrice: "12x R$ 1.181,00",
      pixPrice: "R$ 12.257,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs: 'Especificações para "MacBook Air 15"M4" não encontradas',
    },
    {
      id: 35,
      model: 'MacBook Air 13"M4',
      storage: "(24GB RAM / 512GB SSD)",
      color: 'Cor para "MacBook Air 13"M4" não encontrada',
      battery: "100%",
      originalPrice: "R$ 14.660,78",
      installmentPrice: "12x R$ 1.181,00",
      pixPrice: "R$ 12.257,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs: 'Especificações para "MacBook Air 13"M4" não encontradas',
    },
    {
      id: 36,
      model: 'MacBook Pro 14" M4',
      storage: "(16GB RAM / 512GB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 14.199,56",
      installmentPrice: "12x R$ 1.230,00",
      pixPrice: "R$ 12.769,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 14.2", Chip M4 (10-core CPU, 10-core GPU), 3x Thunderbolt 4, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 38,
      model: 'MacBook Air 13"M4',
      storage: "(16GB RAM / 512GB SSD)",
      color: 'Cor para "MacBook Air 13"M4" não encontrada',
      battery: "100%",
      originalPrice: "R$ 11.230,47",
      installmentPrice: "12x R$ 983,00",
      pixPrice: "R$ 10.201,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs: 'Especificações para "MacBook Air 13"M4" não encontradas',
    },
    {
      id: 39,
      model: 'MacBook Air 15"M4',
      storage: "(16GB RAM / 256GB SSD)",
      color: 'Cor para "MacBook Air 15"M4" não encontrada',
      battery: "100%",
      originalPrice: "R$ 12.397,87",
      installmentPrice: "12x R$ 1.027,00",
      pixPrice: "R$ 10.666,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs: 'Especificações para "MacBook Air 15"M4" não encontradas',
    },
    {
      id: 40,
      model: 'MacBook Air 13"M4',
      storage: "(16GB RAM / 256GB SSD)",
      color: 'Cor para "MacBook Air 13"M4" não encontrada',
      battery: "100%",
      originalPrice: "R$ 9.289,76",
      installmentPrice: "12x R$ 797,00",
      pixPrice: "R$ 8.269,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs: 'Especificações para "MacBook Air 13"M4" não encontradas',
    },
    {
      id: 37,
      model: "iMac M4 24",
      storage: "(16GB RAM / 256GB SSD)",
      color: 'Cor para "iMac M4 24" não encontrada',
      battery: "100%",
      originalPrice: "R$ 14.810,83",
      installmentPrice: "12x R$ 1.246,00",
      pixPrice: "R$ 12.939,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Imacs",
      specs: 'Especificações para "iMac M4 24" não encontradas',
    },
    {
      id: 41,
      model: "Mac Mini M4",
      storage: "(16GB RAM / 512GB SSD)",
      color: "Prateado",
      battery: "100%",
      originalPrice: "R$ 9.250,49",
      installmentPrice: "12x R$ 781,00",
      pixPrice: "R$ 8.110,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Mac Minis",
      specs:
        "Chip M4 (10-core CPU, 10-core GPU), 2x USB-C (frente), 3x Thunderbolt 4 (trás), HDMI, Gigabit Ethernet, Wi-Fi 6E",
    },
    {
      id: 42,
      model: "Mac Mini M4",
      storage: "(16GB RAM / 256GB SSD)",
      color: "Prateado",
      battery: "100%",
      originalPrice: "R$ 7.318,77",
      installmentPrice: "12x R$ 606,00",
      pixPrice: "R$ 6.291,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Mac Minis",
      specs:
        "Chip M4 (10-core CPU, 10-core GPU), 2x USB-C (frente), 3x Thunderbolt 4 (trás), HDMI, Gigabit Ethernet, Wi-Fi 6E",
    },
    {
      id: 43,
      model: 'MacBook Pro 16" M3 Max',
      storage: "(48GB RAM / 1TB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 31.287,85",
      installmentPrice: "12x R$ 2.713,00",
      pixPrice: "R$ 28.166,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 16.2", Chip M3 Max (14/16-core CPU, 30/40-core GPU), 3x Thunderbolt 4, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 44,
      model: 'MacBook Pro 14" M3 Pro',
      storage: "(18GB RAM / 512GB SSD)",
      color: "Prata, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 16.323,30",
      installmentPrice: "12x R$ 1.329,00",
      pixPrice: "R$ 13.791,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 14.2", Chip M3 Pro (11/12-core CPU, 14/18-core GPU), 3x Thunderbolt 4, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 45,
      model: 'MacBook Pro 14" M3',
      storage: "(8GB RAM / 512GB SSD)",
      color: "Prata, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 12.218,92",
      installmentPrice: "12x R$ 1.027,00",
      pixPrice: "R$ 10.666,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina XDR 14.2", Chip M3 (8-core CPU, 10-core GPU), 2x Thunderbolt / USB 4, HDMI, SDXC, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 46,
      model: 'MacBook Air 15" M3',
      storage: "(8GB RAM / 512GB SSD)",
      color: "Prateado, Estelar, Cinza-espacial, Meia-noite",
      battery: "100%",
      originalPrice: "R$ 12.044,58",
      installmentPrice: "12x R$ 995,00",
      pixPrice: "R$ 10.326,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina 15.3", Chip M3 (8-core CPU, 10-core GPU), 2x Thunderbolt / USB 4, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 47,
      model: 'MacBook Air 13" M3',
      storage: "(16GB RAM / 512GB SSD)",
      color: "Prateado, Estelar, Cinza-espacial, Meia-noite",
      battery: "100%",
      originalPrice: "R$ 11.006,85",
      installmentPrice: "12x R$ 929,00",
      pixPrice: "R$ 9.644,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina 13.6", Chip M3 (8-core CPU, 8/10-core GPU), 2x Thunderbolt / USB 4, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 48,
      model: 'MacBook Air 15" M3',
      storage: "(16GB RAM / 256GB SSD)",
      color: "Prateado, Estelar, Cinza-espacial, Meia-noite",
      battery: "100%",
      originalPrice: "R$ 10.836,69",
      installmentPrice: "12x R$ 929,00",
      pixPrice: "R$ 9.644,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina 15.3", Chip M3 (8-core CPU, 10-core GPU), 2x Thunderbolt / USB 4, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 49,
      model: 'MacBook Air 13" M3',
      storage: "(16GB RAM / 256GB SSD)",
      color: "Prateado, Estelar, Cinza-espacial, Meia-noite",
      battery: "100%",
      originalPrice: "R$ 9.188,53",
      installmentPrice: "12x R$ 759,00",
      pixPrice: "R$ 7.882,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina 13.6", Chip M3 (8-core CPU, 8/10-core GPU), 2x Thunderbolt / USB 4, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 50,
      model: 'MacBook Air 13" M2',
      storage: "(8GB RAM / 512GB SSD)",
      color: "Prateado, Estelar, Cinza-espacial, Meia-noite",
      battery: "100%",
      originalPrice: "R$ 8.765,32",
      installmentPrice: "12x R$ 743,00",
      pixPrice: "R$ 7.712,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina 13.6", Chip M2 (8-core CPU, 8/10-core GPU), 2x Thunderbolt / USB 4, MagSafe 3, Wi-Fi 6',
    },
    {
      id: 51,
      model: 'MacBook Air 13" M3',
      storage: "(8GB RAM / 256GB SSD)",
      color: "Prateado, Estelar, Cinza-espacial, Meia-noite",
      battery: "100%",
      originalPrice: "R$ 8.946,02",
      installmentPrice: "12x R$ 743,00",
      pixPrice: "R$ 7.712,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina 13.6", Chip M3 (8-core CPU, 8/10-core GPU), 2x Thunderbolt / USB 4, MagSafe 3, Wi-Fi 6E',
    },
    {
      id: 52,
      model: 'MacBook Air 13" M2',
      storage: "(16GB RAM / 256GB SSD)",
      color: "Prateado, Estelar, Cinza-espacial, Meia-noite",
      battery: "100%",
      originalPrice: "R$ 8.406,42",
      installmentPrice: "12x R$ 683,00",
      pixPrice: "R$ 7.087,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina 13.6", Chip M2 (8-core CPU, 8/10-core GPU), 2x Thunderbolt / USB 4, MagSafe 3, Wi-Fi 6',
    },
    {
      id: 53,
      model: 'MacBook Air 13" M2',
      storage: "(8GB RAM / 256GB SSD)",
      color: "Prateado, Estelar, Cinza-espacial, Meia-noite",
      battery: "100%",
      originalPrice: "R$ 8.195,76",
      installmentPrice: "12x R$ 661,00",
      pixPrice: "R$ 6.860,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Liquid Retina 13.6", Chip M2 (8-core CPU, 8/10-core GPU), 2x Thunderbolt / USB 4, MagSafe 3, Wi-Fi 6',
    },
    {
      id: 54,
      model: "MacBook Air M1",
      storage: "(8GB RAM / 256GB SSD)",
      color: "Dourado, Prateado, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 6.306,84",
      installmentPrice: "12x R$ 522,00",
      pixPrice: "R$ 5.416,00",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Macbooks",
      specs:
        'Tela Retina 13.3", Chip M1 (8-core CPU, 7/8-core GPU), 2x Thunderbolt / USB 4, Wi-Fi 6',
    },
  ],
  ipads: [
    {
      id: 55,
      model: 'iPad Pro 7 13" M4',
      storage: "(1TB / Wi-Fi)",
      color: "Prateado, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 16.167,20",
      installmentPrice: "R$ 1.399",
      pixPrice: "R$ 14.523",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip M4, Tela Ultra Retina XDR 13", Câmeras Pro 12MP (frontal e traseira), Face ID, USB-C (Thunderbolt/USB 4), Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      id: 56,
      model: 'iPad Pro 7 13" M4',
      storage: "512GB",
      color: "Prateado, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 14.440,62",
      installmentPrice: "R$ 1.201",
      pixPrice: "R$ 12.464",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip M4, Tela Ultra Retina XDR 13", Câmeras Pro 12MP (frontal e traseira), Face ID, USB-C (Thunderbolt/USB 4), Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      id: 57,
      model: 'iPad Pro 7 13" M4',
      storage: "256GB",
      color: "Prateado, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 13.026,70",
      installmentPrice: "R$ 1.138",
      pixPrice: "R$ 11.817",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip M4, Tela Ultra Retina XDR 13", Câmeras Pro 12MP (frontal e traseira), Face ID, USB-C (Thunderbolt/USB 4), Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      id: 58,
      model: 'iPad Pro 5 11" M4',
      storage: "256GB",
      color: "Prateado, Preto-espacial",
      battery: "100%",
      originalPrice: "R$ 10.148,43",
      installmentPrice: "R$ 844",
      pixPrice: "R$ 8.758",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip M4, Tela Ultra Retina XDR 11", Câmeras Pro 12MP (frontal e traseira), Face ID, USB-C (Thunderbolt/USB 4), Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      id: 59,
      model: 'iPad Air 6 13" M2',
      storage: "128GB",
      color: "Azul, Roxo, Estelar, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 7.433,11",
      installmentPrice: "R$ 640",
      pixPrice: "R$ 6.641",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip M2, Tela Liquid Retina 13", Câmera frontal 12MP na horizontal (Palco Central), Câmera traseira 12MP, Touch ID, USB-C, Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      id: 60,
      model: 'iPad Air 6 11" M2',
      storage: "256GB",
      color: "Azul, Roxo, Estelar, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 6.410,22",
      installmentPrice: "R$ 560",
      pixPrice: "R$ 5.817",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip M2, Tela Liquid Retina 11", Câmera frontal 12MP na horizontal (Palco Central), Câmera traseira 12MP, Touch ID, USB-C, Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      id: 61,
      model: 'iPad Air 6 11" M2',
      storage: "128GB",
      color: "Azul, Roxo, Estelar, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 5.800,81",
      installmentPrice: "R$ 498",
      pixPrice: "R$ 5.170",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip M2, Tela Liquid Retina 11", Câmera frontal 12MP na horizontal (Palco Central), Câmera traseira 12MP, Touch ID, USB-C, Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      id: 62,
      model: "iPad Mini 7",
      storage: "256GB",
      color: "Azul, Roxo, Estelar, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 5.774,43",
      installmentPrice: "R$ 492",
      pixPrice: "R$ 5.111",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip A17 Pro, Tela Liquid Retina 8.3", Câmera frontal 12MP na horizontal (Palco Central), Câmera traseira 12MP, Touch ID, USB-C, Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      id: 63,
      model: 'iPad Air 5 10,9" M1',
      storage: "64GB",
      color: "Cinza-espacial, Estelar, Rosa, Roxo, Azul",
      battery: "100%",
      originalPrice: "R$ 5.307,50",
      installmentPrice: "R$ 436",
      pixPrice: "R$ 4.523",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip M1, Tela Liquid Retina 10.9", Câmera frontal 12MP (Palco Central), Câmera traseira 12MP, Touch ID, USB-C, Wi-Fi 6, Bluetooth 5.0',
    },

    {
      id: 64,
      model: "iPad Mini 7",
      storage: "128GB",
      color: "Azul, Roxo, Estelar, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 5.163,54",
      installmentPrice: "R$ 424",
      pixPrice: "R$ 4.405",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip A17 Pro, Tela Liquid Retina 8.3", Câmera frontal 12MP na horizontal (Palco Central), Câmera traseira 12MP, Touch ID, USB-C, Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      id: 65,
      model: "iPad 10",
      storage: "256GB",
      color: "Prateado, Azul, Rosa, Amarelo",
      battery: "100%",
      originalPrice: "R$ 4.755,76",
      installmentPrice: "R$ 390",
      pixPrice: "R$ 4.052",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip A14 Bionic, Tela Liquid Retina 10.9", Câmera frontal 12MP na horizontal (Palco Central), Câmera traseira 12MP, Touch ID, USB-C, Wi-Fi 6, Bluetooth 5.2',
    },
    {
      id: 66,
      model: "iPad 9",
      storage: "256GB",
      color: "Prateado, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 4.427,00",
      installmentPrice: "R$ 356",
      pixPrice: "R$ 3.699",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip A13 Bionic, Tela Retina 10.2", Câmera frontal 12MP (Palco Central), Câmera traseira 8MP, Touch ID, Conector Lightning, Wi-Fi 5, Bluetooth 4.2',
    },
    {
      id: 67,
      model: "iPad Mini 6",
      storage: "64GB",
      color: "Cinza-espacial, Rosa, Roxo, Estelar",
      battery: "100%",
      originalPrice: "R$ 4.128,35",
      installmentPrice: "R$ 334",
      pixPrice: "R$ 3.464",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip A15 Bionic, Tela Liquid Retina 8.3", Câmera frontal 12MP (Palco Central), Câmera traseira 12MP, Touch ID, USB-C, Wi-Fi 6, Bluetooth 5.0',
    },
    {
      id: 68,
      model: "iPad 9",
      storage: "64GB",
      color: "Prateado, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 3.739,48",
      installmentPrice: "R$ 322",
      pixPrice: "R$ 3.347",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip A13 Bionic, Tela Retina 10.2", Câmera frontal 12MP (Palco Central), Câmera traseira 8MP, Touch ID, Conector Lightning, Wi-Fi 5, Bluetooth 4.2',
    },
    {
      id: 69,
      model: "iPad 10",
      storage: "64GB",
      color: "Prateado, Azul, Rosa, Amarelo",
      battery: "100%",
      originalPrice: "R$ 3.308,83",
      installmentPrice: "R$ 271",
      pixPrice: "R$ 2.817",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip A14 Bionic, Tela Liquid Retina 10.9", Câmera frontal 12MP na horizontal (Palco Central), Câmera traseira 12MP, Touch ID, USB-C, Wi-Fi 6, Bluetooth 5.2',
    },
    {
      id: 70,
      model: "iPad 9",
      storage: "64GB",
      color: "Prateado, Cinza-espacial",
      battery: "100%",
      originalPrice: "R$ 3.100,66",
      installmentPrice: "R$ 254",
      pixPrice: "R$ 2.641",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "iPads",
      specs:
        'Chip A13 Bionic, Tela Retina 10.2", Câmera frontal 12MP (Palco Central), Câmera traseira 8MP, Touch ID, Conector Lightning, Wi-Fi 5, Bluetooth 4.2',
    },
  ],
  "apple-watch": [
    {
      id: 71,
      model: "Apple Watch Ultra 2 (M.)",
      storage: "(49mm)",
      color: "Titânio Natural (com pulseiras variadas)",
      battery: "100%",
      originalPrice: "R$ 8.676,92",
      installmentPrice: "R$ 738",
      pixPrice: "R$ 7.664",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Apple Watch",
      specs:
        "Chip S9 SiP, Tela Retina Sempre Ativa LTPO OLED (até 3000 nits), GPS de precisão e dupla frequência, Botão de Ação, Sirene, Profundímetro, Sensor de temperatura da água, Oxigênio no Sangue, ECG, Sensor cardíaco óptico, Detecção de Queda/Acidente, Resistência à água 100m, Certificação MIL-STD 810H, Mergulho recreativo até 40m, Wi-Fi 4, Bluetooth 5.3",
    },
    {
      id: 72,
      model: "Apple Watch Ultra 2 (24)",
      storage: "(49mm)",
      color: "Titânio Natural (com pulseiras variadas)",
      battery: "100%",
      originalPrice: "R$ 6.833,39",
      installmentPrice: "R$ 574",
      pixPrice: "R$ 5.960",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Apple Watch",
      specs:
        "Chip S9 SiP, Tela Retina Sempre Ativa LTPO OLED (até 3000 nits), GPS de precisão e dupla frequência, Botão de Ação, Sirene, Profundímetro, Sensor de temperatura da água, Oxigênio no Sangue, ECG, Sensor cardíaco óptico, Detecção de Queda/Acidente, Resistência à água 100m, Certificação MIL-STD 810H, Mergulho recreativo até 40m, Wi-Fi 4, Bluetooth 5.3",
    },
    {
      id: 73,
      model: "Apple Watch Ultra 2 (23)",
      storage: "(49mm)",
      color: "Titânio Natural (com pulseiras variadas)",
      battery: "100%",
      originalPrice: "R$ 6.687,37",
      installmentPrice: "R$ 541",
      pixPrice: "R$ 5.619",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Apple Watch",
      specs:
        "Chip S9 SiP, Tela Retina Sempre Ativa LTPO OLED (até 3000 nits), GPS de precisão e dupla frequência, Botão de Ação, Sirene, Profundímetro, Sensor de temperatura da água, Oxigênio no Sangue, ECG, Sensor cardíaco óptico, Detecção de Queda/Acidente, Resistência à água 100m, Certificação MIL-STD 810H, Mergulho recreativo até 40m, Wi-Fi 4, Bluetooth 5.3",
    },
    {
      id: 74,
      model: "Apple Watch Series 10",
      storage: "(46mm)",
      color: "Meia-noite, Estelar, Prateado, Rosa, (PRODUCT)RED",
      battery: "100%",
      originalPrice: "R$ 3.597,05",
      installmentPrice: "R$ 289",
      pixPrice: "R$ 3.005",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Apple Watch",
      specs:
        "Chip S9 SiP, Tela Retina Sempre Ativa LTPO OLED (até 2000 nits), Oxigênio no Sangue, ECG, Sensor cardíaco óptico, Detecção de Queda/Acidente, Sensor de temperatura, Resistência à água 50m, GPS, Wi-Fi 4, Bluetooth 5.3",
    },
    {
      id: 75,
      model: "Apple Watch Series 10",
      storage: "(42mm)",
      color: "Meia-noite, Estelar, Prateado, Rosa, (PRODUCT)RED",
      battery: "100%",
      originalPrice: "R$ 3.468,37",
      installmentPrice: "R$ 279",
      pixPrice: "R$ 2.892",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Apple Watch",
      specs:
        "Chip S9 SiP, Tela Retina Sempre Ativa LTPO OLED (até 2000 nits), Oxigênio no Sangue, ECG, Sensor cardíaco óptico, Detecção de Queda/Acidente, Sensor de temperatura, Resistência à água 50m, GPS, Wi-Fi 4, Bluetooth 5.3",
    },
    {
      id: 76,
      model: "Apple Watch Series 9",
      storage: "(45mm)",
      color: "Meia-noite, Estelar, Prateado, Rosa, (PRODUCT)RED",
      battery: "100%",
      originalPrice: "R$ 3.242,03",
      installmentPrice: "R$ 261",
      pixPrice: "R$ 2.710",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Apple Watch",
      specs:
        "Chip S9 SiP, Tela Retina Sempre Ativa LTPO OLED (até 2000 nits), Oxigênio no Sangue, ECG, Sensor cardíaco óptico, Detecção de Queda/Acidente, Sensor de temperatura, Resistência à água 50m, GPS, Wi-Fi 4, Bluetooth 5.3",
    },
    {
      id: 77,
      model: "Apple Watch Series 9",
      storage: "(41mm)",
      color: "Meia-noite, Estelar, Prateado, Rosa, (PRODUCT)RED",
      battery: "100%",
      originalPrice: "R$ 3.175,22",
      installmentPrice: "R$ 257",
      pixPrice: "R$ 2.664",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Apple Watch",
      specs:
        "Chip S9 SiP, Tela Retina Sempre Ativa LTPO OLED (até 2000 nits), Oxigênio no Sangue, ECG, Sensor cardíaco óptico, Detecção de Queda/Acidente, Sensor de temperatura, Resistência à água 50m, GPS, Wi-Fi 4, Bluetooth 5.3",
    },
    {
      id: 78,
      model: "Apple Watch SE 2ª Ger",
      storage: "(44mm)",
      color: "Meia-noite, Estelar, Prateado",
      battery: "100%",
      originalPrice: "R$ 2.393,53",
      installmentPrice: "R$ 195",
      pixPrice: "R$ 2.028",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Apple Watch",
      specs:
        "Chip S8 SiP, Tela Retina LTPO OLED (até 1000 nits), Sensor cardíaco óptico, Detecção de Queda/Acidente, Resistência à água 50m, GPS, Wi-Fi 4, Bluetooth 5.3",
    },
    {
      id: 79,
      model: "Apple Watch SE 2ª Ger",
      storage: "(40mm)",
      color: "Meia-noite, Estelar, Prateado",
      battery: "100%",
      originalPrice: "R$ 2.156,39",
      installmentPrice: "R$ 175",
      pixPrice: "R$ 1.812",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Apple Watch",
      specs:
        "Chip S8 SiP, Tela Retina LTPO OLED (até 1000 nits), Sensor cardíaco óptico, Detecção de Queda/Acidente, Resistência à água 50m, GPS, Wi-Fi 4, Bluetooth 5.3",
    },
  ],
  acessorios: [
    {
      id: 80,
      model: "AirPods Max",
      storage: "",
      color: "Cinza-espacial, Prateado, Verde, Azul-celeste, Rosa",
      battery: "100%",
      originalPrice: "R$ 5.207,42",
      installmentPrice: "R$ 424",
      pixPrice: "R$ 4.400",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Chip H1 (em cada fone), Cancelamento Ativo de Ruído, Modo Ambiente, Áudio Espacial com rastreamento dinâmico da cabeça, Equalização Adaptativa, Até 20h de áudio com ANC/Modo Ambiente",
    },
    {
      id: 81,
      model: "AirPods Pro 2ª Geração (Tipo C Magsafe)",
      storage: "Tipo C Magsafe",
      color: "Branco",
      battery: "100%",
      originalPrice: "R$ 2.189,21",
      installmentPrice: "R$ 182",
      pixPrice: "R$ 1.891",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Chip H2, Cancelamento Ativo de Ruído (até 2x melhor), Modo Ambiente Adaptável, Áudio Espacial Personalizado, Controle por Toque, Resistência a poeira, suor e água (IP54), Estojo de carregamento MagSafe (USB-C) com alto-falante e entrada para cordão",
    },
    {
      id: 82,
      model: "AirPods 4 (C/ Noise Cancelation)",
      storage: "C/ Noise Cancelation",
      color: "Branco",
      battery: "100%",
      originalPrice: "R$ 2.232,87",
      installmentPrice: "R$ 182",
      pixPrice: "R$ 1.891",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Chip H2 (provável), Cancelamento Ativo de Ruído, Áudio Espacial, Design atualizado (provável), Estojo de carregamento USB-C (provável)",
    },
    {
      id: 83,
      model: "AirPods 4 (S/ Noise Cancelation)",
      storage: "S/ Noise Cancelation",
      color: "Branco",
      battery: "100%",
      originalPrice: "R$ 1.853,88",
      installmentPrice: "R$ 151",
      pixPrice: "R$ 1.572",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Chip H2 (provável), Áudio Espacial, Design atualizado (provável), Estojo de carregamento USB-C (provável)",
    },
    {
      id: 84,
      model: "AirPods 3",
      storage: "",
      color: "Branco",
      battery: "100%",
      originalPrice: "R$ 1.449,37",
      installmentPrice: "R$ 123",
      pixPrice: "R$ 1.279",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Chip H1, Áudio Espacial com rastreamento dinâmico da cabeça, Equalização Adaptativa, Sensor de força, Resistência a suor e água (IPX4), Estojo de carregamento MagSafe ou Lightning",
    },
    {
      id: 85,
      model: "AirPods 2",
      storage: "",
      color: "Branco",
      battery: "100%",
      originalPrice: "R$ 1.204,73",
      installmentPrice: "R$ 104",
      pixPrice: "R$ 1.083",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Chip H1, Acesso à Siri por voz, Conexão rápida, Até 5h de áudio, Estojo de carregamento Lightning",
    },
    {
      id: 86,
      model: "Apple Pencil Pro",
      storage: "",
      color: "Branco",
      originalPrice: "R$ 1.394,09",
      installmentPrice: "R$ 116",
      pixPrice: "R$ 1.205",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Pareamento e carga sem fio, Precisão absoluta, Sensibilidade à inclinação e pressão, Baixa latência, Gesto de apertar, Rotação do sensor giroscópico, Resposta tátil, Buscar Apple Pencil, Ponta substituível",
    },
    {
      id: 87,
      model: "Apple Pencil 1ª Geração",
      storage: "",
      color: "Branco",
      originalPrice: "R$ 1.226,77",
      installmentPrice: "R$ 105",
      pixPrice: "R$ 1.095",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Pareamento e carga via Lightning, Precisão absoluta, Sensibilidade à inclinação e pressão, Baixa latência, Ponta substituível",
    },
    {
      id: 88,
      model: "AirTag (4 unidades)",
      storage: "4 unidades",
      color: "Branco/Prateado",
      originalPrice: "R$ 1.109,71",
      installmentPrice: "R$ 94",
      pixPrice: "R$ 973",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Chip U1 (Banda Ultralarga e Busca Precisa), Bluetooth LE, Alto-falante integrado, Resistência a água e poeira (IP67), Bateria CR2032 substituível (dura mais de um ano), Integração com app Buscar",
    },
    {
      id: 89,
      model: "Apple Pencil 2ª Geração",
      storage: "",
      color: "Branco",
      originalPrice: "R$ 1.076,06",
      installmentPrice: "R$ 93",
      pixPrice: "R$ 960",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Pareamento e carga magnética, Precisão absoluta, Sensibilidade à inclinação e pressão, Baixa latência, Dois toques para trocar de ferramenta, Ponta substituível",
    },
    {
      id: 90,
      model: "AirTag (1 unidades)",
      storage: "1 unidades",
      color: "Branco/Prateado",
      originalPrice: "R$ 642,93",
      installmentPrice: "R$ 52",
      pixPrice: "R$ 544",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Chip U1 (Banda Ultralarga e Busca Precisa), Bluetooth LE, Alto-falante integrado, Resistência a água e poeira (IP67), Bateria CR2032 substituível (dura mais de um ano), Integração com app Buscar",
    },
    {
      id: 91,
      model: "Fonte Turbo USB-C 20w",
      storage: "",
      color: "Branco",
      originalPrice: "R$ 293,13",
      installmentPrice: "R$ 24",
      pixPrice: "R$ 250",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Adaptador de energia USB-C de 20W, Carregamento rápido para iPhones e iPads compatíveis",
    },
    {
      id: 92,
      model: "Cabo USB-C",
      storage: "",
      color: "Branco",
      originalPrice: "R$ 298,63",
      installmentPrice: "R$ 24",
      pixPrice: "R$ 250",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Cabo de carregamento USB-C para USB-C (1m ou 2m), Suporta carregamento e transferência de dados",
    },
    {
      id: 93,
      model: "Cabo Lightning",
      storage: "",
      color: "Branco",
      originalPrice: "R$ 296,22",
      installmentPrice: "R$ 24",
      pixPrice: "R$ 250",
      details: "aparelho novo",
      image: "",
      realImages: [],
      category: "Acessorios",
      specs:
        "Cabo de USB-C para Lightning ou USB-A para Lightning (1m ou 2m), Suporta carregamento e transferência de dados",
    },
  ],
};

const ProductPage: React.FC = () => {
  const { category, id } = useParams<{ category: string; id: string }>();
  const navigate = useNavigate();
  const [product, setProduct] = useState<any>(null);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    if (category && id) {
      // Buscar produto no banco de dados
      const categoryProducts =
        productDatabase[category as keyof typeof productDatabase];
      if (categoryProducts) {
        const foundProduct = categoryProducts.find(
          (p) => p.id === parseInt(id)
        );
        if (foundProduct) {
          setProduct(foundProduct);
        } else {
          // Produto não encontrado, redirecionar para página de categoria
          navigate(`/${category}`);
        }
      } else {
        // Categoria não encontrada, redirecionar para home
        navigate("/");
      }
    }
    setLoading(false);
  }, [category, id, navigate]);

  if (loading) {
    return <div className="loading">Carregando...</div>;
  }

  if (!product) {
    return <div className="not-found">Produto não encontrado</div>;
  }

  return (
    <PageTransition>
      <ProductDetail product={product} />
    </PageTransition>
  );
};

export default ProductPage;
